import os
import json
import logging
import dspy
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class VeoAdPromptSignature(dspy.Signature):
    """
    You are an elite SNS Advertising Director and Google Vertex AI VEO 2.0 Prompt Engineer.
    Your sole goal is to generate HIGH-CONVERTING, COMMERCIAL-GRADE video prompts to sell a food menu to a specific `target_persona`.
    
    === VEO 2.0 OFFICIAL PROMPT FORMULA ===
    Every scene description MUST explicitly combine:
    [Subject/대상] + [Motion/동작] + [Environment/환경] + [Camera Angle/카메라 앵글] + [Lens Effect/렌즈 및 광학 효과]
    
    === CRITICAL ADVERTISING RULES ===
    1. THE 2-SECOND HOOK: The first scene must be visually explosive (Extreme Close-Up, macro shot of steam, sizzling) to stop SNS scrolling. Apply the `sns_marketing_hook` directive.
    2. VISUAL COPYWRITING: Don't just show food; make it look incredibly appetizing using the `visual_keywords`.
    3. STRICT VEO CAMERA DIRECTING: You must explicitly include the `camera_angle` and `lens_optical_effects` exactly as provided in the prompt text.
    4. PREVENT AI ARTIFACTS: Explicitly enforce the `negative_constraints` (e.g. absolutely NO humans, hands, or faces allowed) to avoid rendering issues.
    5. ABSOLUTELY NO HUMANS: You must strictly obey the `food_focus_rule`. Never generate humans, hands, or utensils. Focus 100% of the cinematic motion on the product itself (steam, lighting, dynamic movement).
    6. VISION SYNC: Match the video exactly to the user's uploaded photo using the `image_visual_context` (colors, plating, lighting).
    7. 8-SECOND IMPACT: The video generated by Veo is strictly 8 seconds long. Do not write a slow, static, or boring scene. Force extreme dynamic motion (e.g., 'crashing', 'bursting', 'whip pan', 'sizzling') to create hyper-cinematic commercial tension.
    8. PERSONA OVER QUALITY: Prioritize making the food look hyper-realistic, visceral, and relatable to the `target_persona` over making it look like a generic 'luxurious' CF. Provide a visceral context.
    
    === AUDIO SCRIPT RULE ===
    9. AUDIO GENERATION: You MUST write a short, punchy Korean audio script (`audio_script`) that perfectly matches the `target_persona` and vibe. It should be 1-2 sentences of exclamation or narration (e.g., "와, 뚝배기 끓는 소리 미쳤다! 국물 한 입 하실래요?").
    """
    target_persona = dspy.InputField(desc="The target customer persona (Korean). Use this STRICTLY to determine the mood, lighting, and environmental vibe. DO NOT include humans.")
    concept = dspy.InputField(desc="The core food menu/concept (Korean). Translate into mouth-watering, appetizing visual English.")
    target_vibe = dspy.InputField(desc="The desired advertising style: 에너지 (fast, viral), 프리미엄 (slow, luxury CF), or 무드 (emotional storyteller).")
    
    # Ad Hook
    sns_marketing_hook = dspy.InputField(desc="Explicit instruction on how to hook the viewer in the first 2 seconds based on the vibe.")
    
    # Veo Official Camera Directing
    camera_angle = dspy.InputField(desc="REQUIRED Camera angles to use (e.g., Extreme Close-up, Bird's-eye view, Dutch angle).")
    lens_optical_effects = dspy.InputField(desc="REQUIRED Lens choices and optical effects (e.g., Macro lens, 85mm telephoto, shallow depth of field, dolly zoom).")
    visual_keywords = dspy.InputField(desc="Key visual ingredients and lighting styles that must permeate the prompt.")
    
    # Constraints
    food_focus_rule = dspy.InputField(desc="Rule defining how to depict the food vs. the human without artificial weirdness.")
    negative_constraints = dspy.InputField(desc="Strict list of visual anomalies to explicitly avoid generating.")
    image_visual_context = dspy.InputField(desc="Detailed visual analysis extracted from the user's uploaded photo (use colors, textures, lighting).")
    
    # Output Formulation
    rationale = dspy.OutputField(desc="Strategic Plan: (1) How does the Hook work? (2) How are the official Veo 'Subject+Motion+Environment+Angle+Lens' applied? (3) How are negative constraints enforced?")
    final_veo_json = dspy.OutputField(desc="A valid JSON string matching the Master Template: title(Korean), hashtags(Korean array), metadata, key_elements(English array), negative_prompts(English array), timeline(Array of scenes incorporating the VEO formula).")
    audio_script = dspy.OutputField(desc="A punchy, 1-2 sentence Korean voiceover/exclamation script tailored to the target_persona and conveying the emotional vibe. e.g. '와, 이 국물 미쳤다!'")
class LLMService:
    def __init__(self):
        # 1. API 키 및 모델 설정
        self.api_key = os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            logger.warning("⚠️ 경고: GEMINI_API_KEY가 없습니다.")
        
        # dspy-ai 설정 (Gemini 2.5 Flash를 사용하여 속도 최적화)
        dspy.settings.configure(
            lm=dspy.LM('gemini/gemini-2.5-flash', api_key=self.api_key)
        )
        
        # 기존 클라이언트 속성 (멀티모달 이미지 분석)
        self.raw_client = genai.Client(api_key=self.api_key)
        
        # 최적화 모듈 (광고 특화 서명 사용)
        self.optimizer = dspy.ChainOfThought(VeoAdPromptSignature)

        # 2. 템플릿 로드
        self.templates = {}
        try:
            with open("templates.json", "r", encoding="utf-8") as f:
                data = json.load(f)
                for t in data.get("templates", []):
                    self.templates[t["id"]] = t
            logger.info(f"✅ Loaded {len(self.templates)} templates.")
        except Exception as e:
            logger.error(f"⚠️ Failed to load templates.json: {e}")

    async def _extract_image_context(self, image_path: str) -> str:
        """Vision Pre-processing using Gemini 2.5 Flash Vision."""
        if not image_path or not os.path.exists(image_path):
            return "No reference image provided. Rely purely on the text prompt."

        print(f"\n📸 [LLM Service] Vision Pre-processing: Analyzing image → {image_path}")
        logger.info(f"📸 Vision Pre-processing: Analyzing image → {image_path}")
        try:
            with open(image_path, "rb") as img_file:
                image_bytes = img_file.read()

            image_part = types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg")
            vision_prompt = """Describe this food image in EXTREME DETAIL across these dimensions:
1. **Food Items**: Colors, textures (glossy, matte, crispy, steaming), sauce viscosity.
2. **Environment & Plating**: Plate material, background textures, atmospheric depth.
3. **Lighting & Shadows**: Direction of light, warmth, specular highlights.
4. **Dominant Color Palette**.
Your description will be used as the absolute visual truth for an AI video commercial."""

            pre_response = self.raw_client.models.generate_content(
                model="gemini-2.5-flash",
                contents=[vision_prompt, image_part]
            )
            return pre_response.text
        except Exception as img_err:
            logger.error(f"⚠️ Vision Pre-processing failed: {img_err}")
            return "Image analysis unavailable."

    async def optimize_payload(self, payload: dict, image_path: str = None) -> dict:
        """
        Optimize the VeoPayload JSON precisely for SNS Advertising & Official VEO structure.
        """
        print("\n🧠 [LLM Service] DSPy SNS Advertising & VEO Optimization Pipeline Starting...")
        logger.info("🧠 DSPy SNS Advertising & VEO Optimization Pipeline Starting...")

        try:
            metadata = payload.get("metadata", {})
            key_elements = payload.get("key_elements", [])
            concept_input = key_elements[0] if len(key_elements) > 0 else "Our signature dish"
            persona_input = key_elements[1] if len(key_elements) > 1 else "A happy customer"

            vibe_id = metadata.get("vibe_id", "energetic")
            selected_template = self.templates.get(vibe_id, self.templates.get("energetic", {}))
            
            # Extract Advanced Advertising & Camera Attributes
            t_angle = selected_template.get("camera_angle", "Medium shot")
            t_lens = selected_template.get("lens_optical_effects", "Standard 50mm")
            t_hook = selected_template.get("sns_marketing_hook", "Create a visually striking SNS hook.")
            t_keywords = selected_template.get("visual_keywords", "Vibrant, Commercial Quality")
            t_negative = selected_template.get("negative_prompt", "blurry, text overlay")
            t_food_rule = selected_template.get("food_focus_rule", "Focus on food texture over eating mechanics.")

            # Vision Context extraction
            image_context = await self._extract_image_context(image_path)

            vibe_label_map = {
                "energetic": "에너지 (SNS Viral 릴스/쇼츠 스타일, 빠른 템포 훅)",
                "luxury": "프리미엄 (CF 광고 스타일, 고급 시네마틱 렌즈 워크)",
                "emotional": "무드 (인스타그램 감성 스토리, 따뜻한 렌즈 플레어)"
            }
            target_vibe_label = vibe_label_map.get(vibe_id, "에너지")

            # Execute DSPy optimization
            logger.info(f"💡 Applying VEO Camera: {t_angle} | {t_lens}")
            logger.info(f"📢 Injecting SNS Hook: {t_hook[:100]}...")

            prediction = self.optimizer(
                target_persona=persona_input,
                concept=concept_input,
                target_vibe=target_vibe_label,
                sns_marketing_hook=t_hook,
                camera_angle=t_angle,
                lens_optical_effects=t_lens,
                visual_keywords=t_keywords,
                food_focus_rule=t_food_rule,
                negative_constraints=t_negative,
                image_visual_context=image_context
            )
            
            logger.info(f"💡 DSPy Commercial Rationale:\n{prediction.rationale}")
            
            try:
                # Cleanup and loading
                clean_text = prediction.final_veo_json.replace("```json", "").replace("```", "").strip()
                optimized_json = json.loads(clean_text)
                return optimized_json
            except json.JSONDecodeError as decode_err:
                logger.error(f"⚠️ JSON Parse Error: {decode_err}\nRaw output: {prediction.final_veo_json}")
                return payload

        except Exception as e:
            logger.error(f"⚠️ DSPy Optimization Failed: {str(e)}")
            return payload
